name: qradar_mobile
description: "QRadar — Real-Time Quishing Detection & Defense Mobile Application"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  image_picker: ^1.0.7
  mobile_scanner: ^5.1.1
  fl_chart: ^0.66.2
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  url_launcher: ^6.2.5
  font_awesome_flutter: ^10.7.0
  google_fonts: ^6.1.0
  uuid: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
